[[constraint]]
  name = "github.com/inconshreveable/log15"
  version = "2.13"

[[constraint]]
  name = "github.com/kevinburke/nacl"
  version = "0.5"

[[constraint]]
  name = "github.com/kevinburke/go-types"
  version = "0.20.0"

[[constraint]]
  name = "github.com/kevinburke/handlers"
  version = "0.32.0"

[[constraint]]
  branch = "master"
  name = "github.com/kevinburke/raven-go"

[[constraint]]
  name = "github.com/kevinburke/rest"
  version = "1.0.0"

[[constraint]]
  name = "github.com/kevinburke/twilio-go"
  version = "0.65.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
